services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./runtime:/root/runtime
      - ./gopen/${ENV}:/root/gopen/${ENV}
    environment:
      - ENV=${ENV}
    restart: no