services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./runtime:/root/runtime
      - ./gopen/${ENV}:/root/gopen/${ENV}
    environment:
      - ENV=${ENV}
      - ELASTIC_APM_SERVICE_NAME=api-gateway
      - ELASTIC_APM_CAPTURE_BODY=all
      - ELASTIC_APM_SERVER_URL=http://apm_server:8200
    restart: no
    logging:
      driver: gelf
      options:
        gelf-address: udp://host.docker.internal:12201
    depends_on:
      - apm_server
    networks:
      - gopen-network
  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    volumes:
      - ./internal/infra/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "12201:12201/udp"
    networks:
      - gopen-network
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - gopen-network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    ports:
      - "5601:5601"
    networks:
      - gopen-network
  apm_server:
    image: docker.elastic.co/apm/apm-server:7.14.1
    ports:
      - 8200:8200
    networks:
      - gopen-network
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.14.1
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./metricbeat.docker.yml
        target: /usr/share/metricbeat/metricbeat.yml
    depends_on:
      - elasticsearch
    command: metricbeat -e -strict.perms=false
    networks:
      - gopen-network
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.14.1
    volumes:
      - type: bind
        source: ./heartbeat.docker.yml
        target: /usr/share/heartbeat/heartbeat.yml
    command: heartbeat -e -strict.perms=false
    networks:
      - gopen-network
networks:
  gopen-network: